### ISSUE TITLE
Consider bringing back "HoSC and the bigger picture" in the future episode

### ISSUE THREAD

**Issue by bast** [coderefinery/instructor-training#110]
Got removed in #102 and I probably removed too much there.

**Comment by rkdarst** [comment]
I don't have computer now, but to me the most important part is connecting
all of the different teaching and providing connections and a map through
them.  perhaps second is connecting to those providing other infra or
services (but this doesn't need to be mentioned here). The HoSC project is
just an implementation... if this can be connected directly to CR then that
is best.

But of course we have to decide this first!  Is it just me?  How much
carpentries stuff to build on here - is this their thing?

**Comment by bast** [comment]
I think providing a map and a bigger picture is a good idea. This week, this summary and future session is only planned to take 20 minutes so there is not much time to discuss any details but I can mention that CodeRefinery is only part of a bigger picture. Please help me then not to forget this. I should be able to manage to commit some summary of this before Thursday.

**Comment by rkdarst** [comment]
I can easily do it before Thursday, too.

**Comment by bast** [comment]
Done in #114.
