### ISSUE TITLE
teaching competent practitioners is harder

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/instructor-training#132]
teaching competent practitioners is harder than novices, because they will tend to be competent or expert in some things, but not others.  The more prerequisites you have, the greater likelihood that
- Any one person will be missing at least one of them (they can't follow your course, or slow you down)
- You have to take the time to explain every pre-requisite
- A noticeable fraction of people will be very bored if you try to deal with the above.

This is from recent experience and I think worth commenting on in the teaching styles episode.  And this starts being important at the coderefinery and hpc-carpentry level.

This can be relevant to teaching style, lesson design, and how-to-teaching

**Comment by annefou** [comment]
I disagree. Teaching competent practitioners is still much easier than teaching novices (in terms of acquisitions of new skills/notions). I think you are talking about the difficulty to manage a wide range of skills. In CR we try to add additional exercises.

**Comment by rkdarst** [comment]
> I disagree. Teaching competent practitioners is still much easier than teaching novices (in terms of acquisitions of new skills/notions). I think you are talking about the difficulty to manage a wide range of skills. In CR we try to add additional exercises.

Hm, could we say that the preparation is different (or harder)?  I
guess "harder" is a very subjective word and perhaps shouldn't be
used.  The quote my colleague came up with was "every course becomes a
basic course" if you don't manage the diversity of backgrounds well?

I guess I can refine my point above: a competent practitioner isn't
usually competent at everything, learners can be novices and competent
in different things, and in essence you still have to plan for novices
in many aspects.  As opposed to (for example) an academic degree
program, where if someone is missing prerequisites then they are
wrong.  I would usually call them different and think about what
prerequisites are really needed.

**Comment by annefou** [comment]
Yes!

**Comment by rkdarst** [comment]
From @annefou: https://github.com/coderefinery/instructor-training/pull/142#discussion_r515625086
It is a big problem to believe one can deliver a workshop for both novices and competent practitioners.

**Comment by rkdarst** [comment]
This topic could be added to teaching philosohpies (perhaps removing some more generic material since this is likely to be more useful and make things too long?).

**Comment by annefou** [comment]
I also added (no PR yet) some information about the target audience in the lesson design.
