### ISSUE TITLE
Workshop preparation and organization: backwards design

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/instructor-training#135]
Please comment on the below (I will also be editing the original post as I get more ideas).

Duration: 30 minutes in schedule now

Episode goals (summative assessments):
- Understand the CodeRefinery way of scaling
  - installation help time
  - helpers
  - breakout rooms and teams 
  - questions via hackmd
- Understand the roles of instructor, host, hackmd, expert helper, helpers
- Understand what you have to do already at registration/preparation time, in order to make this work
  - make learner personas and prerequisites clear
  - team registration, powerful enough registration system
- Practicalities of zoom, hackmd, learner prep,  (link to manual pages)

Exercise:
- List everything you have seen gone wrong with a workshop

**Comment by annefou** [comment]
I think it is very good.  The exercise is a bit too vague. Maybe we should also ask something like: what do you suggest as mitigation measures?
