### ISSUE TITLE
Top issues new instructor face

### ISSUE THREAD

**Issue by bast** [coderefinery/instructor-training#137]
From our hackmd:

- Breaks are not negotiable, minimum 10 minutes.
- Breakout sessions too short. Make them as long as possible, don't expect to come back for new intro, then go back.
- People will accomplish less than you expect.  Expect learners to be 5 times slower than you, at best!
- All the other tools and stuff will go wrong. Try to not bring in a dependency when you don't need it.
- Trying to accomplish too much: it's OK to cut out and adapt to the audience.  Have a reserve session at the end you prepare, but are ready to skip.
- Explaining how, but not why.
- Running out of time to making your environment match the learner's.
- Running out of time to set up good screen sharing practices
  (terminal history, portion of screen, remote history) in advance.
- Assuming learners remember what they have already learned, or know the prerequisites.  Or have stuff installed and configured.
- Not managing expectations: learners think that you will accomplish everything, and feel sad when you don't.

I think we should add these as "hidden" solution to the material. @Sabryr leads this group work on Monday. Please let me know if you need help with this.

**Comment by rkdarst** [comment]
I also plan to put this in the manuals (need to move and commit...),
but I think it would make sense to have it here, too.  Unless you want
to link to the manuals location.

**Comment by Sabryr** [comment]
Should I use this as an intro before the group work ?

**Comment by Sabryr** [comment]
-  Get the speed correct. Not too fast and not too slow.
-  Special issues when lessons delivered online (more details of the appear in  Workshop preparation and organization I guess), 
   -  proper microphone settings, 
    - screen sharing settings, 
    - how to get feed back from learners during lessons
