### ISSUE TITLE
pre-workshop survey

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/instructor-training#175]
We probably already have one, but if not we should.  What would have been useful this time?

- which of the sections are you interested in: teaching philosophy, teaching practice, lesson design, software tools for lesson design, hands-on lesson editing, how coderefinery runs workshops, how to invite and host a coderefinery workshop.

- previous experience in teaching (what type)

- future teaching plans

...

**Comment by bast** [comment]
We have used this in the past: https://github.com/coderefinery/instructor-training/blob/master/survey-questions.md

But fully agree that we should ask the above questions.
