### ISSUE TITLE
develop material for sustainability episode

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/instructor-training#23]
https://coderefinery.github.io/instructor_training/05-partnership/

**Comment by wikfeldt** [comment]
ah, see now that Radovan opened #20 
@bast are you working on it or should i work on an initial draft?

**Comment by bast** [comment]
It's very welcome and super appreciated if you write a draft. I will not have time to work on this anyway before Thursday/Friday I fear.

**Comment by bast** [comment]
From https://github.com/coderefinery/instructor_training/pull/25#issuecomment-547356542
> Would this be a good place to mention our/my grand plan of connecting CodeRefinery (teaching), RSEs (hands-on support), and NordicHPC (usable infra) in a complete nordic scientific computing package (and ask how to make that possible)?

**Comment by bast** [comment]
Stealing this issue from Thor.

**Comment by bast** [comment]
This is now drafted (thanks Thor and Richard). I will work more on this today but the issue can IMO be closed.
