### ISSUE TITLE
develop material for how to contribute material

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/instructor-training#24]
i.e. this episode:
https://coderefinery.github.io/instructor_training/04-lessons/

**Comment by rkdarst** [comment]
Now it's here: https://coderefinery.github.io/instructor-training/06-lessons/

There are some basics but needs continued revisions.

**Comment by bast** [comment]
I will do an iteration on this today.

**Comment by bast** [comment]
I consider this done in #70. It's not perfect but a good starting point and presentable IMO.
