### ISSUE TITLE
Hand-on scicomp

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/instructor-training#26]
I'd like to mention https://handsonscicomp.readthedocs.io/ sometime.  It could cover:
- what it is, how it relates to other projects
- how to contribute, what is needed
- it should be a international, multi-site project, how to facilitate that?

**Comment by bast** [comment]
Are you going to draft it or do you prefer if somebody else does?

**Comment by rkdarst** [comment]
I'll draft it, I think I'm going to have a few hours this afternoon
now... I hope...

Anyway I'll do it eventually.

**Comment by rkdarst** [comment]
It's now mentioned, #58.
