### ISSUE TITLE
question on "Carpentries versus CodeRefinery audience" exercise

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/instructor-training#39]
https://coderefinery.github.io/instructor_training/02-teachingstyle/#exercise-carpentries-versus-coderefinery-audience
I'm not sure about the idea behind the exercise. Can you clarify @annefou ?

**Comment by rkdarst** [comment]
When I was reading the exercise, I thought "this is probably supposed to make readers think about how we teach higher-level skills (higher levels of bloom's taxonomy), so we need our audience to already have a knowledge of basic use of the skill (programming)".  Blooms's taxonomy isn't introduced there yet, but it leads to it right below.  And, how we will have to correct misconceptions more often that SWC's instructors will have to.

Just my idea.

**Comment by annefou** [comment]
Yes you are right. That's exactly what I had in mind.

**Comment by wikfeldt** [comment]
ok that sounds good. Closing the issue
