### ISSUE TITLE
sustainability vs future

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/instructor-training#64]
What do you think about the relation of these sections?  Should the material be re-adjusted in any way?

I think it's overall pretty logical now if we consider sustainability=CR funding, but there is a chance it could be adjusted.

**Comment by rkdarst** [comment]
I was going to add this to future but it may be better in sustainability, thus this is an appropriate place to discuss it: somewhere we should ask the question "how to embed within university daily operations?"

**Comment by bast** [comment]
I think this is fixed in #102.
