### ISSUE TITLE
some of the exercises in teaching-style are repeated in teaching episode

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/instructor-training#76]
e.g. concept maps, ILOs etc
we should remove redundancies between 
https://coderefinery.github.io/instructor-training/02-teachingstyle/
and 
https://coderefinery.github.io/instructor-training/08-teaching/

**Comment by annefou** [comment]
I am reducing 02-teachingstyle to focus on CodeRefinery teaching approach and give an overall overview of the Carpentries teaching approach.

**Comment by bast** [comment]
Since #101 this repetition is removed.
