### ISSUE TITLE
Preparation: update "practicals"

### ISSUE THREAD

**Issue by bast** [coderefinery/instructor-training#79]
Make it clearer what to prepare for an online event and what to prepare for a physical event.

**Comment by annefou** [comment]
What would be the difference? I think we could have the same perrequisites for both onlien and face 2 face workshops.

**Comment by bast** [comment]
I agree. We should have the same. The motivation for this issue was that the practicals were outdated and me not understanding back then that this workshop can be designed for online-first and still work in-person using the same tools.

**Comment by bast** [comment]
Updated in #103.
