### ISSUE TITLE
Teaching: focus on teaching skills, live coding

### ISSUE THREAD

**Issue by bast** [coderefinery/instructor-training#93]
Concept map seems misplaced here.

Consider moving some of the many exercises to other episodes. Now there is too much choice.

**Comment by annefou** [comment]
@bast this issue is a bit unclear (to me); where is "here"?

**Comment by bast** [comment]
Sorry I probably meant this https://coderefinery.github.io/instructor-training/02-teachingstyle/#concept-mapping. It is a good exercise but at least when we went through material during the open house in March, this felt a bit in the wrong place/time to do this.
