### ISSUE TITLE
Survey questions for instructor training

### ISSUE THREAD

**Issue by bast** [coderefinery/instructor-training#95]
Maybe this is not the right repo but I don't want to lose these good questions that we use for the workshop with TU Delft:
- have you participated in the Carpentries instructor training?
- have you participated at a Carpentries workshop?
  - as an instructor?
  - as a helper?
- have you participated at a CodeRefinery workshop?
  - as a learner?
  - as a helper?
- what do you most often teach?
- what do you think you will teach later?
- what do you see people most often missing, that should be taught somewhere?

**Comment by bast** [comment]
@annefou here are the questions but they got some updates which I will post here in a moment.

**Comment by bast** [comment]
These are the questions that were actually sent out:
- Are you familiar with the teaching style of The Carpentries (Software or Data) workshops?*
  - Yes
  - No
- Have you participated at a Carpentries workshop?*- they can choose more than one
  - as an instructor (certified or not)
  - as a helper
  - as a learner
- Are you a certified instructor of The Carpentries?*
  - Yes
  - No
- Have you participated at a CodeRefinery workshop?* - they can choose more than one
  - as a learner
  - as a helper
- Do you provide training about software/code management and sharing best practices?*
  - Yes
  - No
- If yes, which topics do you include in your training?
  - free text
- Which topics would you like to include in the future in your training?
  - free text
- What do you think are topics around software/code management and sharing best practices that 
  researchers are often missing that should be taught somewhere?
  - free text

**Comment by annefou** [comment]
Excellent. who is creating/in charge of the survey? CodeRefinery or DUDelft?

**Comment by bast** [comment]
They are in charge of the registration (this will lower coordination since almost all participants are on their side) but we were promised to get the results of the survey.

**Comment by bast** [comment]
Sorry my answer was not very clear, they are also in charge of creating and collecting the survey.

**Comment by annefou** [comment]
Ok. Do we have a link to the survey?

**Comment by bast** [comment]
Not yet and I think the survey is part of the registration form but we will be later able to link to the registration form (I think it is going out today). For me it's important that we somehow keep these good questions for future events.

**Comment by naoe-tatara** [comment]
I wonder if there is some sort of standard format of a survey that could be imported to any survey application, but it was not easy to find such thing at least.
If it is fine, I can make a md file in the root directory (? not sure if it is called so, but right under this repository, I mean), so that those interested in can review and suggest changes?

**Comment by bast** [comment]
Indico uses JSON but right now Markdown would already be great and then next time we organize the event (and the registration), we can import it into Indico and save it as JSON.

**Comment by naoe-tatara** [comment]
I interpreted that the survey was already made and sent (and probably collected) at TU-Delft, and thus no need to make a new file for now, but thanks for the follow up :)

**Comment by bast** [comment]
I still think we need to save this as a file but it is not very urgent now.

**Comment by bast** [comment]
Saved in #106.
